[package]
name = "bevy_support_misc"
version = "0.2.0"
authors = ["Trung Do <dothanhtrung@pm.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/kimtinh/bevy-support.git"
keywords = ["bevy"]
description = ""
exclude = ["assets", "examples", "tests", ".cargo"]
categories = ["game-development"]

[dependencies]
bevy = { version = "0.15", features = ["bevy_ui"], default-features = false }

[dev-dependencies]
bevy = { version = "0.15" }

[features]
default = []
3d = []