[package]
name = "bevy_support_misc"
version = "0.7.1"
authors = ["Trung Do <dothanhtrung@pm.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/kimtinh/bevy-support-misc.git"
keywords = ["bevy"]
description = "My tiny common code to share between bevy game projects"
exclude = ["assets", "examples", "tests", ".cargo"]
categories = ["game-development"]

[dependencies]
bevy = { version = ">=0.17", features = ["bevy_ui", "bevy_color", "bevy_text", "bevy_state"], default-features = false }
ron = { version = "0.12", optional = true }
thiserror = { version = "2.0", optional = true }
serde = { version = "1.0", optional = true }
postcard = { version = "1.1" , features = ["alloc"], optional = true }

[dev-dependencies]
bevy = { version = ">=0.17" }

[features]
default = []
3d = []
log = ["bevy/bevy_log"]
ron_loader = ["ron", "thiserror", "serde"]
bincode_loader = ["postcard", "thiserror", "serde"]